name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build ImTool
      run: dotnet build -c Release ImTool/ImTool.csproj
      
    - name: Publish ImTool nuget
      uses: rohith/publish-nuget@v2
      if: github.event_name != 'pull_request'
      with:
        PROJECT_FILE_PATH: ImTool/ImTool.csproj
        PACKAGE_NAME: ImTool
        NUGET_KEY: ${{secrets.TMW_NUGET}}
